Repository atlp-rwanda/phantom-fe-techode, pull requests merged in 2022-03, with the labels that each got.

#20 Update driver or operator profile #TP-39
  package-lock.json
  package.json
  src/App.js
  src/__test__/App.test.js
  src/__test__/Logout.test.js
  src/__test__/Profile.test.js
  src/__test__/integrationTest/index.test.js
  src/__test__/roles.test.js
  src/assets/svgs/deletePermission.svg
  src/assets/svgs/lebals/info.svg
  src/assets/svgs/lebals/priveleges.svg
  src/assets/svgs/lebals/profile.svg
  src/components/buttons/Buttons.js
  src/components/buttons/LebalButton.js
  src/components/fields/TextField.js
  src/components/header/DashBoardHeader.js
  src/components/logout/Logout.js
  src/components/passwordReset/newpassword.js
  src/components/passwordReset/passwordereset.js
  src/components/roles/Roles.js
  src/components/skeletons/Tables/TablePermissionsSkeleton.js
  src/components/skeletons/Tables/TableRolesSkeleton.js
  src/components/svgs/locate.svg
  src/components/svgs/setrole.svg
  src/containers/Home/Home.js
  src/containers/RegisterDriverOperator/RegisterDriver.js
  src/containers/RegisterDriverOperator/RegisterOperator.js
  src/containers/profile/Profile.js
  src/functions/Notify.js
  src/redux/actions/permissionAction.js
  src/redux/actions/roleAction.js
  src/redux/actions/userActions.js
  src/redux/constants/permissionActionType.js
  src/redux/constants/roleAction.js
  src/redux/constants/userActionTypes.js
  src/redux/reducers/index.js
  src/redux/reducers/permissionsReducer.js
  src/redux/reducers/rolesReducer.js
  src/redux/reducers/userReducer.js
  src/redux/store.js
  src/utls/testStore.js
Labels: WIP, Done, Feedback Completed

#21 Ft permissions tp 32
  package-lock.json
  package.json
  src/__test__/__snapshots__/roles.test.js.snap
  src/__test__/reducers/rolesReducer.test.js
  src/__test__/roles.test.js
  src/components/roles/Roles.js
  src/components/signIn/LoginForm.js
  src/redux/reducers/rolesReducer.js
Labels: WIP, Done, Feedback Completed

#25 #TP-35 ft: assign drivers to buses
  .env
  package-lock.json
  package.json
  server.js
  src/App.js
  src/__test__/App.test.js
  src/__test__/reducers/assignBusReducer.test.js
  src/components/pagination/Pagination.js
  src/components/roles/Roles.js
  src/components/sidebar/SideBar.js
  src/containers/OperatorDriverBus/OperatorAssignBus.js
  src/containers/RegisterBus/RegisterBus.js
  src/redux/actions/assignBusAction.js
  src/redux/constants/assignBusActionTypes.js
  src/redux/reducers/assignBusReducer.js
  src/redux/reducers/index.js
  webpack.config.js
Labels: WIP, Done

#22 #TP-37 ft:Bus motion simulation
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__test__/App.test.js
  src/__test__/Signin.test.js
  src/__test__/__snapshots__/busSimulation.test.js.snap
  src/__test__/busSimulation.test.js
  src/__test__/integrationTest/intergration.test.js
  src/__test__/reducers/busSimulationReducers.test.js
  src/assets/style/style-skeleton.css
  src/assets/svgs/busLink.svg
  src/assets/svgs/locationInfo.svg
  src/assets/svgs/navigation/bus.svg
  src/assets/svgs/navigation/onBoardBus.svg
  src/assets/svgs/navigation/stoppedBus.svg
  src/components/BusSim/BusSim.js
  src/components/Cards/RouteCard.js
  src/components/LocationSim/DriverSim.js
  src/components/LocationSim/LocationSim.js
  src/components/LocationSim/locationSimUpdate.js
  src/components/LocationSim/map-style-driver.css
  src/components/LocationSim/map-style.css
  src/components/buttons/Buttons.js
  src/components/buttons/LebalButton.js
  src/components/dashBoardLayout/DashBoardLayout.js
  src/components/header/DashBoardHeader.js
  src/components/icons/Icons.js
  src/components/roles/Roles.js
  src/components/sidebar/SideBar.js
  src/components/signIn/LoginForm.js
  src/components/skeletons/SkeletonLogout.js
  src/components/skeletons/cards/TrackCard.js
  src/containers/BusSimulation/BusSimulation.js
  src/containers/Dashboard/Dashboard.js
  src/containers/Home/Home.js
  src/containers/profile/Profile.js
  src/functions/BusTrack.js
  src/functions/Notify.js
  src/functions/RanderMyLocation.js
  src/functions/RoutingMachine.js
  src/redux/actions/ActiveBus.js
  src/redux/actions/selectedRouteAction.js
  src/redux/constants/activeBusActionTypes.js
  src/redux/constants/selectedRouteActionTypes.js
  src/redux/reducers/SelectedRouteReducer.js
  src/redux/reducers/activeBusReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/userReducer.js
  tailwind.config.js
Labels: Ready For Review

#29 #TP-35 ft: assign drivers to buses notifications
  package-lock.json
  package.json
  public/index.html
  src/__test__/App.test.js
  src/__test__/reducers/assignBusReducer.test.js
  src/assets/svgs/notification.svg
  src/components/dashBoardLayout/DashBoardLayout.js
  src/components/dashBoardLayout/DashboardOperatorLayout.js
  src/components/header/DashBoardHeader.js
  src/components/notification/Notification.js
  src/components/pagination/Pagination.js
  src/components/roles/Roles.js
  src/containers/OperatorDriverBus/OperatorAssignBus.js
  src/functions/Notify.js
  src/index.js
  src/redux/actions/notificationAction.js
  src/redux/constants/notificationActionTypes.js
  src/redux/reducers/assignBusReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/notificationReducer.js
  tailwind.config.js
Labels: Done, Ready For Review

#27 #TP-34 ft: CRUD operations for routes
  package-lock.json
  package.json
  src/App.js
  src/__test__/App.test.js
  src/__test__/reducers/routesReducer.test.js
  src/assets/img/Vector.png
  src/assets/img/Vector2.png
  src/assets/img/deleteRoute.png
  src/assets/img/editRoute.png
  src/assets/img/imageBus.png
  src/assets/img/location_route.png
  src/assets/img/profile_admin.png
  src/assets/style/main.css
  src/components/RoutesTable.js
  src/components/buttons/Buttons.js
  src/containers/OperatorDriverBus/OperatorAssignBus.js
  src/containers/RegisterDriverOperator/RegisterOperator.js
  src/containers/Routes/AddRoute.js
  src/containers/Routes/DeleteRoute.js
  src/containers/Routes/RouteInfoSkeleton.js
  src/containers/Routes/Routemap.css
  src/functions/GetRouteInfo.js
  src/redux/actions/RoutesAction.js
  src/redux/constants/RouteActionType.js
  src/redux/reducers/RoutesReducer.js
  src/redux/reducers/index.js
Labels: Done
