Repository atlp-rwanda/phantom-fe-techode, pull requests merged in 2022-05, with the labels that each got.

#34 ft(intergration) Create roles and set permissions
  .github/workflows/develop.yml
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/__test__/__snapshots__/roles.test.js.snap
  src/__test__/reducers/rolesReducer.test.js
  src/__test__/roles.test.js
  src/api/index.js
  src/components/passwordReset/newpassword.js
  src/components/permission/Permission.js
  src/components/roles/Roles.js
  src/components/sidebar/SideBar.js
  src/containers/BusSimulation/BusSimulation.js
  src/containers/OperatorDriverBus/OperatorAssignBus.js
  src/containers/RegisterDriverOperator/RegisterDriver.js
  src/containers/RegisterDriverOperator/RegisterOperator.js
  src/containers/SignIn/LoginForm.js
  src/containers/busesOp/Busesoperat.js
  src/redux/actions/accountActions.js
  src/redux/actions/permissionAction.js
  src/redux/actions/roleAction.js
  src/redux/constants/permissionActionType.js
  src/redux/constants/roleAction.js
  src/redux/reducers/permissionsReducer.js
  src/redux/reducers/rolesReducer.js
  src/utls/getPermissionId.js
Labels: need review

#41 Ft(integration) crud operation buses
  src/__test__/reducers/busesOpReducers.test.js
  src/components/roles/Roles.js
  src/containers/SignIn/LoginForm.js
  src/containers/busesOp/Busesoperat.js
  src/redux/actions/busAction.js
  src/redux/constants/busActionType.js
  src/redux/reducers/busesReducer.js
Labels: WIP, Ready For Review

#40 #TP-23 ft:CRUD operation for routes
  src/__test__/reducers/routesReducer.test.js
  src/containers/Routes/AddRoute.js
  src/redux/actions/RoutesAction.js
  src/redux/constants/RouteActionType.js
  src/redux/reducers/RoutesReducer.js
  src/skeleton/skeletonElement.js
Labels: need review

#43 TP-21 ft(assign) drivers to buses
  package-lock.json
  src/__test__/reducers/rolesReducer.test.js
  src/api/index.js
  src/containers/OperatorDriverBus/OperatorAssignBus.js
  src/redux/reducers/userReducer.js
Labels: Ready For Review

#46 #TP-25 ft: improve landing page
  src/__test__/Home.test.js
  src/components/Cards/CardTestimonial.css
  src/components/Cards/CardTestimonial.js
  src/components/Cards/CardToStart.css
  src/components/Cards/CardToStart.js
  src/components/Explore/Explore.css
  src/components/Explore/Explore.js
  src/components/Footer/Footer.js
  src/components/HowToStart/HowToStart.js
  src/components/Intro/Intro.js
  src/components/Services/Services.js
  src/components/Testimonials/Testimonials.js
  src/containers/Home/Home.js
Labels: Ready For Review

#47 ft:refactor routes and buses
  package-lock.json
  src/__test__/__snapshots__/busesOperat.test.js.snap
  src/__test__/busesOperat.test.js
  src/components/header/DashBoardHeader.js
  src/containers/Routes/AddRoute.js
  src/containers/busesOp/Busesoperat.js
Labels: Ready For Review

#45 #TP-19 ft(update) Profile information
  package-lock.json
  src/__test__/Logout.test.js
  src/api/index.js
  src/components/fields/TextField.js
  src/components/logout/Logout.js
  src/containers/SignIn/LoginForm.js
  src/containers/profile/Profile.js
  src/redux/reducers/userReducer.js
Labels: Ready For Review
